(() => {
'use strict';
const B=window.BOARDS, $=id=>document.getElementById(id), KEY='friends-jeopardy-game-v1';
const COLORS=['#8963a3','#c77b42','#568576','#6587ac','#b8667f','#9a8a3e'];
const DEFAULT_NAMES=['The Lobsters','The Transponsters','Smelly Cats','Unagi Masters','Central Perks','Holiday Armadillos'];
const fresh=()=>({version:1,started:false,board:0,played:{},teams:[],timer:0,penalties:false,sound:false,history:[],active:null});
let S=fresh(),timerId=null,timerEnd=0,timerRemaining=0,timerRunning=false,toastId,ctx,setupMode='start',pendingBoard=0,lastFocus=null;
const validKey=k=>/^[0-2]-[0-4]-[0-4]$/.test(k);
try { const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&saved.version===1){S={...fresh(),...saved};S.board=Number.isInteger(S.board)&&S.board>=0&&S.board<3?S.board:0;S.played=Object.fromEntries(Object.entries(S.played||{}).filter(([k,v])=>validKey(k)&&v));S.teams=Array.isArray(S.teams)?S.teams.slice(0,6).map((t,i)=>({name:String(t.name||DEFAULT_NAMES[i]).slice(0,24),score:Number.isFinite(t.score)?t.score:0})):[];S.timer=[0,15,30,60].includes(S.timer)?S.timer:0;S.history=Array.isArray(S.history)?S.history.filter(h=>h&&validKey(h.key)&&Array.isArray(h.scores)).slice(-75):[];if(!S.active||!validKey(S.active.key))S.active=null;}}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S));}catch{toast('Browser storage unavailable. Keep this tab open to retain progress.');}}
function esc(s){const d=document.createElement('span');d.textContent=s;return d.innerHTML;}
const key=(b,c,q)=>`${b}-${c}-${q}`;
const value=q=>(q+1)*100;
const money=n=>(n<0?'−':'')+'$'+Math.abs(n).toLocaleString('en-US');
const count=b=>Object.keys(S.played).filter(k=>k.startsWith(b+'-')).length;
const total=()=>Object.keys(S.played).length;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastId);toastId=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function tone(kind){if(!S.sound)return;try{ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();const notes=kind==='win'?[523,659,784,1047]:kind==='reveal'?[440,554,659]:kind==='time'?[330,262]:[392,523];notes.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.085;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.035,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.19);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+.2);});}catch{}}
function syncSound(){$('soundButton').setAttribute('aria-pressed',String(S.sound));$('soundButton').innerHTML=`${S.sound?'♫':'♪'} <span>Sound ${S.sound?'on':'off'}</span>`;$('soundButton').setAttribute('aria-label',`Turn sound ${S.sound?'off':'on'}`);}
function screen(id){document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('hidden',e.id!==id));window.scrollTo(0,0);}
function home(){stopTimer();renderPreviews();$('startButton').innerHTML=S.started?'Resume game <span>↗</span>':'Let’s play <span>↗</span>';$('newButton').classList.toggle('hidden',!S.started);screen('home');}
function renderPreviews(){$('previews').innerHTML=B.map((b,i)=>`<button class="preview" data-preview="${i}"><div class="preview-top"><span class="preview-icon" aria-hidden="true">${b.icon}</span><span class="preview-number">BOARD 0${i+1}</span></div><h2>${esc(b.title)}</h2><p>${esc(b.subtitle)}</p><div class="preview-bottom"><span>${count(i)?`${count(i)} / 25 PLAYED`:'5 CATEGORIES · 25 CLUES'}</span><span class="preview-arrow" aria-hidden="true">↗</span></div></button>`).join('');}
function renderScores(){if(!S.teams.length){$('scoreboard').innerHTML='<p class="micro">Clues-only mode · Enjoy the trivia at your own pace.</p>';return;}const high=Math.max(...S.teams.map(t=>t.score));$('scoreboard').innerHTML=S.teams.map((t,i)=>`<div class="score ${t.score===high&&total()?'leader':''}" style="--team:${COLORS[i]}"><div class="score-name">${esc(t.name)}</div><div class="score-value">${money(t.score)}</div></div>`).join('');}
function showBoard(b=S.board,focus=true){stopTimer();S.board=b;save();$('boardTabs').innerHTML=B.map((_,i)=>`<button aria-pressed="${i===b}" data-board="${i}">Board 0${i+1}</button>`).join('');$('roundLabel').textContent=`EPISODE 0${b+1} / 03 · ${B[b].icon}`;$('boardTitle').textContent=B[b].title;$('boardDescription').textContent=B[b].subtitle;$('progressText').textContent=`${count(b)} of 25 clues played`;$('progressBar').style.width=`${count(b)*4}%`;$('board').innerHTML=B[b].categories.map(c=>`<div class="category"><span aria-hidden="true">${c.icon}</span>${esc(c.name)}</div>`).join('')+Array.from({length:5},(_,q)=>B[b].categories.map((c,i)=>`<button class="tile ${S.played[key(b,i,q)]?'played':''}" style="--delay:${(q*5+i)*9}ms" data-clue="${i}-${q}" ${S.played[key(b,i,q)]?'disabled':''} aria-label="${esc(c.name)}, ${value(q)} points${S.played[key(b,i,q)]?', played':''}">${S.played[key(b,i,q)]?'✓<small>PLAYED</small>':money(value(q))}</button>`).join('')).join('');$('completeBanner').classList.toggle('hidden',count(b)!==25);if(count(b)===25){$('completeBanner').innerHTML=`<span>✓ Board complete. ${total()===75?'That’s all 75. Take a bow.':'The couch is impressed. Ready for another?'}</span><button class="text-btn" id="continueButton">${total()===75?'See final scores →':'Next unfinished board →'}</button>`;$('continueButton').onclick=()=>total()===75?finale():showBoard(B.findIndex((_,i)=>count(i)<25));}$('undoButton').disabled=!S.history.length;renderScores();screen('game');if(focus)$('boardTitle').focus({preventScroll:true});}
function openClue(c,q){const k=key(S.board,c,q);if(S.played[k])return;S.active={key:k,revealed:false,penalized:[],scores:S.teams.map(t=>t.score)};save();tone('open');renderClue();}
function activeData(){const [b,c,q]=S.active.key.split('-').map(Number);return {b,c,q,cat:B[b].categories[c],data:B[b].categories[c].clues[q]};}
function renderClue(){if(!S.active)return showBoard();const {b,q,cat,data}=activeData();$('clueBoard').textContent=`BOARD 0${b+1}`;$('clueCategory').textContent=`${cat.icon} ${cat.name}`;$('clueValue').textContent=money(value(q));$('question').textContent=data.question;$('answer').textContent=data.answer;$('reference').textContent=data.reference||'';$('answerArea').classList.toggle('hidden',!S.active.revealed);$('revealArea').classList.toggle('hidden',S.active.revealed);$('judgeArea').classList.toggle('hidden',!S.active.revealed);$('clueLabel').textContent=S.active.revealed?'THE CLUE · REVEALED':'THE CLUE';$('backButton').textContent=S.active.revealed?'← Finish clue & return':'← Back to board';renderJudging();screen('clue');resetTimerUI();$('question').focus({preventScroll:true});}
function renderJudging(){const v=value(activeData().q);$('judgePrompt').textContent=S.teams.length?'Who got it?':'Got it? Keep the memories coming.';$('judgeTeams').innerHTML=S.teams.map((t,i)=>`<div class="judge-team" style="--team:${COLORS[i]}"><strong>${esc(t.name)}</strong><button data-correct="${i}" ${S.active.penalized.includes(i)?'disabled':''} aria-label="Award ${v} points to ${esc(t.name)}">+${money(v)} ✓</button>${S.penalties?`<button class="wrong" data-wrong="${i}" ${S.active.penalized.includes(i)?'disabled':''} aria-label="Subtract ${v} points from ${esc(t.name)}">${S.active.penalized.includes(i)?'Deducted':'−'+money(v)}</button>`:''}</div>`).join('');$('skipButton').textContent=S.teams.length?'No one got it · Next clue →':'Mark played · Back to board →';$('judgeHint').innerHTML=S.penalties&&S.teams.length?'Mark incorrect teams first, then award the correct team. '+(S.active.penalized.length?'<button class="text-btn" id="clearPenalties">Undo deductions</button>':''):'Awarding a team completes this clue. Scores can be undone from the board.';if(!S.teams.length)$('judgeHint').textContent='Your progress is saved on this device.';if($('clearPenalties'))$('clearPenalties').onclick=()=>{S.teams.forEach((t,i)=>t.score=S.active.scores[i]);S.active.penalized=[];save();renderJudging();};}
function reveal(){if(!S.active||S.active.revealed)return;stopTimer();S.active.revealed=true;save();renderClue();tone('reveal');$('skipButton').focus({preventScroll:true});}
function deduct(i){if(!S.active?.revealed||!S.penalties||S.active.penalized.includes(i)||!S.teams[i])return;S.teams[i].score-=value(activeData().q);S.active.penalized.push(i);save();renderJudging();}
function finish(winner=null){if(!S.active)return;if(!S.active.revealed)return leaveClue();const a=S.active,{b,q}=activeData();if(winner!==null){if(!S.teams[winner]||a.penalized.includes(winner))return;S.teams[winner].score+=value(q);tone('win');}S.history.push({key:a.key,scores:a.scores});S.history=S.history.slice(-75);S.played[a.key]=true;S.active=null;save();if(total()===75){finale();return;}showBoard(b,false);const next=$('board').querySelector('.tile:not(:disabled)');(next||$('boardTitle')).focus({preventScroll:true});if(count(b)===25){celebrate();tone('win');}}
function leaveClue(){if(!S.active)return showBoard();if(S.active.revealed)return finish();const {b,c,q}=activeData();S.active=null;save();showBoard(b,false);$('board').querySelector(`[data-clue="${c}-${q}"]`)?.focus({preventScroll:true});}
function undo(){const h=S.history.pop();if(!h)return;delete S.played[h.key];S.teams.forEach((t,i)=>{t.score=h.scores[i]??t.score;});S.active=null;save();showBoard(Number(h.key[0]));toast('Last clue reopened. Scores restored.');}
function stopTimer(){clearInterval(timerId);timerId=null;timerRunning=false;}
function resetTimerUI(){stopTimer();timerRemaining=S.timer;$('timerBar').style.width='0%';$('timerStatus').textContent='';$('timerButton').disabled=!S.timer||S.active?.revealed;$('timerButton').textContent=S.timer?`Start ${S.timer}s timer`:'Timer off';}
function timerTick(){timerRemaining=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));$('timerButton').textContent=`Pause · ${timerRemaining}s`;$('timerBar').style.width=`${timerRemaining/S.timer*100}%`;$('timerStatus').textContent=`${timerRemaining} seconds left`;if(timerRemaining<=0){stopTimer();$('timerButton').textContent='Restart timer';$('timerStatus').textContent='Time’s up! Host, call the answer when you’re ready.';tone('time');}}
function toggleTimer(){if(!S.timer||S.active?.revealed)return;if(timerRunning){stopTimer();$('timerButton').textContent=`Resume · ${timerRemaining}s`;return;}if(timerRemaining<=0)timerRemaining=S.timer;timerEnd=Date.now()+timerRemaining*1000;timerRunning=true;timerTick();timerId=setInterval(timerTick,200);}
function showSetup(mode='start',b=0){setupMode=mode;pendingBoard=b;$('setupTitle').textContent=mode==='settings'?'Your game, your rules.':'Make yourselves at home.';$('setupSubmit').textContent=mode==='settings'?'Save settings →':'Start game →';$('teamCount').value=S.started?S.teams.length:2;$('teamCount').disabled=mode==='settings'&&total()>0;$('timerSetting').value=S.timer;$('penaltySetting').value=S.penalties?'yes':'no';renderFields();$('setupDialog').showModal();}
function renderFields(){const previous=Array.from($('teamFields').querySelectorAll('input')).map(x=>x.value);$('teamFields').innerHTML=Array.from({length:Number($('teamCount').value)},(_,i)=>`<div><label for="team${i}">Team ${i+1}</label><input id="team${i}" maxlength="24" value="${esc(previous[i]??S.teams[i]?.name??DEFAULT_NAMES[i])}" style="--team:${COLORS[i]}" autocomplete="off"></div>`).join('');}
function start(b){if(!S.started)return showSetup('start',b);if(S.active)return renderClue();showBoard(b);}
function confirmNew(){$('resetDialog').showModal();}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<45;i++){const el=document.createElement('i');el.className='confetti';el.style.cssText=`left:${Math.random()*100}%;background:${COLORS[i%6]};--drift:${Math.random()*200-100}px;animation-delay:${Math.random()*.4}s`;document.body.append(el);setTimeout(()=>el.remove(),2600);}}
function finale(){stopTimer();const sorted=S.teams.map((t,i)=>({...t,i})).sort((a,b)=>b.score-a.score);$('finalScores').innerHTML=sorted.map((t,i)=>`<div class="rank-row"><strong>${i===0||t.score===sorted[0].score?'🏆 ':''}${esc(t.name)}</strong><span>${money(t.score)}</span></div>`).join('');screen('finale');celebrate();tone('win');}
$('startButton').onclick=()=>start(S.board);$('newButton').onclick=confirmNew;$('homeButton').onclick=()=>{if(S.active){if(S.active.revealed)finish();else{S.active=null;save();}}home();};$('previews').onclick=e=>{const btn=e.target.closest('[data-preview]');if(btn)start(Number(btn.dataset.preview));};$('boardTabs').onclick=e=>{const btn=e.target.closest('[data-board]');if(btn)showBoard(Number(btn.dataset.board));};$('board').onclick=e=>{const btn=e.target.closest('[data-clue]');if(btn&&!btn.disabled)openClue(...btn.dataset.clue.split('-').map(Number));};$('revealButton').onclick=reveal;$('backButton').onclick=leaveClue;$('skipButton').onclick=()=>finish();$('judgeTeams').onclick=e=>{const correct=e.target.closest('[data-correct]'),wrong=e.target.closest('[data-wrong]');if(correct)finish(Number(correct.dataset.correct));if(wrong)deduct(Number(wrong.dataset.wrong));};$('timerButton').onclick=toggleTimer;$('teamsButton').onclick=()=>showSetup('settings',S.board);$('teamCount').onchange=renderFields;
$('setupForm').onsubmit=e=>{e.preventDefault();const n=Number($('teamCount').value);S.teams=Array.from({length:n},(_,i)=>({name:$(`team${i}`).value.trim()||DEFAULT_NAMES[i],score:setupMode==='settings'?(S.teams[i]?.score||0):0}));S.timer=Number($('timerSetting').value);S.penalties=$('penaltySetting').value==='yes';S.started=true;$('setupDialog').close();save();tone('open');showBoard(pendingBoard);};
$('undoButton').onclick=undo;$('resetButton').onclick=confirmNew;$('againButton').onclick=confirmNew;$('reviewButton').onclick=()=>showBoard(S.board);$('confirmReset').onclick=()=>{const sound=S.sound;S=fresh();S.sound=sound;$('teamFields').replaceChildren();save();$('resetDialog').close();home();showSetup();};$('rulesButton').onclick=()=>{lastFocus=document.activeElement;$('rulesDialog').showModal();};document.querySelectorAll('[data-close]').forEach(btn=>btn.onclick=()=>btn.closest('dialog').close());$('soundButton').onclick=()=>{S.sound=!S.sound;save();syncSound();tone('open');};$('fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Fullscreen isn’t supported here. Try your browser’s fullscreen control.');}};
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(!$('clue').classList.contains('hidden')){if(e.code==='Space'&&!S.active.revealed){e.preventDefault();reveal();}else if(e.key==='Escape'){e.preventDefault();leaveClue();}}});
syncSound();home();if(S.active)renderClue();
})();
