/* Run with Playwright installed. Optional CHROMIUM_PATH points at an existing browser. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||process.cwd()]}));
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const f=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',f.endsWith('.css')?'text/css':f.endsWith('.js')?'text/javascript':f.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('friends-jeopardy-game-v1')));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1080},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.screenshot({path:'/tmp/friends-home.png',fullPage:true});
await page.locator('#startButton').click();await page.locator('#team0').fill('Lobsters " & <3');await page.locator('#penaltySetting').selectOption('yes');await page.locator('#timerSetting').selectOption('15');await page.locator('#setupSubmit').click();assert.equal(await page.locator('.tile').count(),25);await page.screenshot({path:'/tmp/friends-board.png',fullPage:true});
await page.locator('[data-clue="0-0"]').click();assert.equal(await page.locator('#answerArea').isVisible(),false);await page.keyboard.press('Escape');assert.equal(Object.keys((await state(page)).played).length,0);
await page.locator('[data-clue="0-0"]').click();await page.clock.install();await page.locator('#timerButton').click();await page.clock.fastForward(16000);assert.match(await page.locator('#timerStatus').textContent(),/Time’s up/);assert.equal(await page.locator('#answerArea').isVisible(),false);await page.keyboard.press('Space');await page.locator('[data-wrong="0"]').click();assert.equal((await state(page)).teams[0].score,-100);await page.locator('#clearPenalties').click();assert.equal((await state(page)).teams[0].score,0);await page.locator('[data-wrong="0"]').click();await page.reload();assert.equal(await page.locator('#answerArea').isVisible(),true);assert.equal((await state(page)).teams[0].score,-100);await page.locator('[data-correct="1"]').click();assert.deepEqual((await state(page)).teams.map(t=>t.score),[-100,100]);assert.equal(Object.keys((await state(page)).played).length,1);await page.locator('#undoButton').click();assert.deepEqual((await state(page)).teams.map(t=>t.score),[0,0]);assert.equal(Object.keys((await state(page)).played).length,0);
await page.locator('[data-clue="0-0"]').click();await page.locator('#revealButton').click();await page.screenshot({path:'/tmp/friends-answer.png',fullPage:true});await page.locator('#skipButton').click();await page.locator('#teamsButton').click();assert.equal(await page.locator('#teamCount').isDisabled(),true);assert.equal(await page.locator('#team0').inputValue(),'Lobsters " & <3');await page.locator('#team0').fill('Team Unagi');await page.locator('#setupSubmit').click();assert.equal((await state(page)).teams[0].name,'Team Unagi');await page.locator('#resetButton').click();await page.locator('#resetDialog [data-close]').click();assert.equal(Object.keys((await state(page)).played).length,1);await page.locator('#resetButton').click();await page.locator('#confirmReset').click();await page.locator('#teamCount').selectOption('0');await page.locator('#setupSubmit').click();assert.equal((await state(page)).teams.length,0);
for(let b=0;b<3;b++){await page.locator(`[data-board="${b}"]`).click();for(let q=0;q<5;q++)for(let c=0;c<5;c++){await page.locator(`[data-clue="${c}-${q}"]`).click();await page.locator('#revealButton').click();await page.locator('#skipButton').click();}if(b<2)assert.equal(await page.locator('#completeBanner').isVisible(),true);}
assert.equal(Object.keys((await state(page)).played).length,75);assert.equal(await page.locator('#finale').isVisible(),true);await page.locator('#reviewButton').click();await page.locator('#undoButton').click();assert.equal(Object.keys((await state(page)).played).length,74);assert.equal((await state(page)).board,2);await page.reload();await page.locator('#startButton').click();assert.equal(await page.locator('.tile:not(:disabled)').count(),1);
await page.setViewportSize({width:390,height:844});await page.locator('#homeButton').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/friends-mobile-home.png',fullPage:true});await page.locator('#startButton').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/friends-mobile-board.png',fullPage:true});await page.locator('.tile:not(:disabled)').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/friends-mobile-clue.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: 75-clue playthrough, scoring, penalties, undo, refresh recovery, timer, reset, escaped names, mobile overflow, and zero JS errors.');await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1);});
